import {BASELINE_PROJECTS} from "./projects-data.js";

const PHASES = [
  {key:"anlass",label:"Anlass / Prüfauftrag",short:"Anlass",className:"p1"},
  {key:"machbarkeit",label:"Machbarkeitsstudie",short:"MBS",className:"p2"},
  {key:"planerwahl",label:"Planerauswahl",short:"Planer",className:"p3"},
  {key:"planung",label:"Planung / Projektierung",short:"Planung",className:"p4"},
  {key:"vergabe",label:"Ausschreibung / Vergabe",short:"Vergabe",className:"p5"},
  {key:"realisierung",label:"Realisierung",short:"Bau",className:"p6"},
  {key:"abschluss",label:"Abschluss / Übergabe",short:"Abschluss",className:"p7"}
];
const NORM_MILESTONES = [
  {key:"auftrag",name:"Prüfauftrag erteilt",phase:0,owner:"Baukommission"},
  {key:"bhb",name:"Bauherrenbegleitung mandatiert",phase:1,owner:"Baukommission"},
  {key:"mbs",name:"Machbarkeitsstudie abgeschlossen",phase:1,owner:"Baukommission"},
  {key:"gate1",name:"Variante und Planung freigegeben",phase:1,owner:"Gesamtvorstand",major:true},
  {key:"planer",name:"Planer ausgewählt",phase:2,owner:"Baukommission"},
  {key:"planung",name:"Planung abgeschlossen",phase:3,owner:"Baukommission"},
  {key:"gate2",name:"Projekt nach Planung freigegeben",phase:3,owner:"Gesamtvorstand",major:true},
  {key:"ausschreibung",name:"Ausschreibung abgeschlossen",phase:4,owner:"Baukommission"},
  {key:"vergabe",name:"Vergabe erfolgt",phase:4,owner:"Baukommission"},
  {key:"baustart",name:"Baustart",phase:5,owner:"Baukommission"},
  {key:"abnahme",name:"Abnahme",phase:6,owner:"Baukommission"},
  {key:"uebergabe",name:"Übergabe und Abschluss",phase:6,owner:"Baukommission"}
];
const START_QUARTER = "2026-Q3";
const DISPLAY_QUARTERS = makeQuarters(START_QUARTER,12);
const ALL_QUARTERS = makeQuarters("2026-Q1",44);
const STORE_KEY = "bgr-portfolio-cockpit-v2";
const HISTORY_KEY = "bgr-portfolio-cockpit-v2-history";
const EXAMPLE_CAPACITIES = [
  {id:"cap-iris-27q1",name:"Iris",function:"BK",quarter:"2027-Q1",min:4,max:6},
  {id:"cap-iris-27q2",name:"Iris",function:"BK",quarter:"2027-Q2",min:8,max:10},
  {id:"cap-tresto-27q1",name:"TRESTO",function:"BHB",quarter:"2027-Q1",min:15,max:20},
  {id:"cap-tresto-27q2",name:"TRESTO",function:"BHB",quarter:"2027-Q2",min:2,max:8}
];

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const clone = value => JSON.parse(JSON.stringify(value));
const esc = value => String(value ?? "").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const num = value => {const n=Number(String(value??"").replace(/[’'\s]/g,"").replace(",","."));return Number.isFinite(n)?n:0};
const chf = (value,short=false) => {const n=num(value);if(!n)return "offen";if(short&&n>=1e6)return `CHF ${(n/1e6).toLocaleString("de-CH",{maximumFractionDigits:1})} Mio.`;if(short&&n>=1e3)return `CHF ${(n/1e3).toLocaleString("de-CH",{maximumFractionDigits:0})} Tsd.`;return new Intl.NumberFormat("de-CH",{style:"currency",currency:"CHF",maximumFractionDigits:0}).format(n)};
function qIndex(q){const m=String(q).match(/(\d{4})-Q([1-4])/);return m?Number(m[1])*4+Number(m[2])-1:0}
function qFromIndex(index){return `${Math.floor(index/4)}-Q${index%4+1}`}
function makeQuarters(start,count){const first=qIndex(start);return Array.from({length:count},(_,i)=>qFromIndex(first+i))}
function qLabel(q){const [y,n]=q.split("-Q");return `Q${n} ${y}`}
function phaseIndex(key){return Math.max(0,PHASES.findIndex(p=>p.key===key))}
function phaseFromLegacy(value){const v=String(value||"");if(v.includes("21"))return "machbarkeit";if(v.includes("PW"))return "planerwahl";if(/31|32|33/.test(v))return "planung";if(v.includes("41"))return "vergabe";if(/51|52/.test(v))return "realisierung";if(v.includes("53"))return "abschluss";if(v.includes("U"))return "realisierung";return "anlass"}
function inferKind(p){const t=`${p.measure} ${p.object}`.toLowerCase();if(p.phase?.includes("U")||(/küchengeräte|fernwärmeanschluss|einfache badsanierung|kurzfristige unterhalt/.test(t)&&p.currentOwner==="Geschäftsstelle"))return "Kleinprojekt";return "Bauprojekt"}
function inferRoles(p){return {gs:p.currentOwner==="Geschäftsstelle"?"Geschäftsstelle":"offen",bk:p.bgrResponsibility==="Baukommission"?(p.currentOwner||"Baukommission"):"offen",vs:"nach Bedarf",bhb:["Büro 8","Tresto","andere externe Partner"].includes(p.projectManagement)?p.projectManagement:"offen",control:p.control||"offen",deputy:p.deputy||"offen"}}
function normalizeProject(p){
  const startYear=Math.max(2026,parseInt(p.startYear,10)||2026);const endYear=parseInt(p.endYear,10)||startYear;
  const project={...clone(p),kind:p.kind||inferKind(p),phaseKey:p.phaseKey||phaseFromLegacy(p.phase),startQuarter:p.startQuarter||`${startYear}-Q${startYear===2026?3:1}`,endQuarter:p.endQuarter||`${Math.max(startYear,endYear)}-Q4`,roles:p.roles||inferRoles(p),demands:Array.isArray(p.demands)?p.demands:[],quarterCosts:Array.isArray(p.quarterCosts)?p.quarterCosts:[],approved:p.approved||"no"};
  project.milestones=Array.isArray(p.milestones)&&p.milestones.length?p.milestones:defaultMilestones(project);
  return project;
}
function defaultMilestones(project){const start=qIndex(project.startQuarter),end=Math.max(start,qIndex(project.endQuarter)),span=Math.max(1,end-start);return NORM_MILESTONES.map((m,i)=>({...m,quarter:qFromIndex(Math.min(end,start+Math.round(span*i/(NORM_MILESTONES.length-1))))}))}
function phaseAt(project,quarter){const qi=qIndex(quarter),start=qIndex(project.startQuarter),end=qIndex(project.endQuarter);if(qi<start||qi>end)return null;const current=Math.max(0,phaseIndex(project.phaseKey));const anchor=Math.max(start,qIndex(START_QUARTER));if(qi<anchor)return Math.max(0,current-1);const remaining=Math.max(1,end-anchor+1),phasesLeft=Math.max(1,PHASES.length-current);return Math.min(PHASES.length-1,current+Math.floor((qi-anchor)/(remaining/phasesLeft)))}
function knownCost(project){const quarter=project.quarterCosts.reduce((s,x)=>s+num(x.amount),0);if(quarter)return quarter;const flows=project.cashflow||[];const known=flows.filter(x=>x.status==="bekannt").reduce((s,x)=>s+num(x.amount),0);return known||num(project.cost)}
function activeSoon(p){return qIndex(p.endQuarter)>=qIndex(START_QUARTER)&&qIndex(p.startQuarter)<=qIndex(DISPLAY_QUARTERS.at(-1))}
function readiness(p){const missing=[];if(!p.startQuarter||!p.endQuarter)missing.push("Zeit");if(!knownCost(p)&&p.kind==="Bauprojekt")missing.push("Geld");if(activeSoon(p)&&!p.demands.length)missing.push("Ressourcen");if(p.kind==="Bauprojekt"&&phaseIndex(p.phaseKey)>=1&&(!p.roles.bhb||p.roles.bhb==="offen"))missing.push("BHB");return {missing,label:missing.length?`${missing.length} Punkte offen`:"Nächste Phase prüfbar"}}

const BASELINE = BASELINE_PROJECTS.map(normalizeProject);
let state=loadState();let history=loadHistory();let selectedId=state.projects[0]?.id;let longOpen=false;let editDemands=[];let editCosts=[];let editMilestones=[];
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY)||"null");if(saved?.projects)return {...saved,projects:saved.projects.map(normalizeProject)};}catch{}return {projects:clone(BASELINE),capacities:clone(EXAMPLE_CAPACITIES),deletedIds:[]}}
function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]")}catch{return []}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll()}
function snapshot(label){history.push({label,state:clone(state)});history=history.slice(-12);localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}
function changedProject(p){const b=BASELINE.find(x=>x.id===p.id);return !b||JSON.stringify(p)!==JSON.stringify(b)}
function changeCount(){return state.projects.filter(changedProject).length+state.deletedIds.length+(JSON.stringify(state.capacities)!==JSON.stringify(EXAMPLE_CAPACITIES)?1:0)}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2200)}

function renderAll(){renderHeader();renderTimeline();renderDetail();renderResources();renderFinance()}
function renderHeader(){
  const near=state.projects.filter(activeSoon);const pressure=near.filter(p=>readiness(p).missing.length);const cost=state.projects.reduce((s,p)=>s+knownCost(p),0);const changes=changeCount();
  $("#data-state").textContent=changes?`${changes} lokale Änderungen`:"Excel Ausgangsstand";
  $("#kpis").innerHTML=[
    ["Vorhaben",state.projects.length,"gesamt"],["Nächste 36 Monate",near.length,"quartalsweise"],["Klärungsbedarf",pressure.length,"vor nächster Phase"],["Bekannte Kosten",chf(cost,true),"Portfolio"],["Verfügbarkeit",state.capacities.length,"Quartalswerte"]
  ].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");
  $("#undo").disabled=!history.length;
}
function filteredProjects(){const search=$("#search").value.trim().toLowerCase(),kind=$("#kind-filter").value,phase=$("#phase-filter").value,pressure=$("#only-pressure").checked;return state.projects.filter(p=>(!search||`${p.object} ${p.measure}`.toLowerCase().includes(search))&&(kind==="all"||p.kind===kind)&&(phase==="all"||p.phaseKey===phase)&&(!pressure||readiness(p).missing.length))}
function renderTimeline(){
  const list=filteredProjects().sort((a,b)=>qIndex(a.startQuarter)-qIndex(b.startQuarter)||a.object.localeCompare(b.object,"de"));
  $("#phase-legend").innerHTML=PHASES.map(p=>`<span><i class="${p.className}"></i>${p.short}</span>`).join("");
  const header=`<div class="timeline-header"><div>${list.length} Projekte</div>${DISPLAY_QUARTERS.map(q=>`<div>${qLabel(q)}</div>`).join("")}</div>`;
  const rows=list.map(p=>{const ready=readiness(p);return `<div class="timeline-row ${p.id===selectedId?"selected":""}" data-select="${esc(p.id)}"><div class="project-label"><strong>${esc(p.object)}</strong><span>${esc(p.measure)} · ${esc(p.kind)}</span>${ready.missing.length?'<i class="pressure-dot" title="Klärungsbedarf"></i>':""}</div>${DISPLAY_QUARTERS.map(q=>{const ix=phaseAt(p,q);if(ix===null)return '<div class="qcell"><i class="empty-cell"></i></div>';const phase=PHASES[ix],gate=(ix===1||ix===3)&&p.milestones.some(m=>m.major&&m.quarter===q);return `<div class="qcell"><div class="phase-block ${phase.className} ${gate?"gate":""}" title="${esc(phase.label)}">${phase.short}</div></div>`}).join("")}</div>`}).join("");
  $("#timeline").innerHTML=header+(rows||`<div class="empty-note">Keine Projekte entsprechen dem Filter.</div>`);
  renderLongHorizon();
}
function renderLongHorizon(){const years=[2030,2031,2032,2033,2034,2035,2036,"10+"];$("#long-horizon").classList.toggle("hidden",!longOpen);$("#expand-long").textContent=longOpen?"Jahre 4–10 ausblenden":"Jahre 4–10 einblenden";$("#long-horizon").innerHTML=`<div class="long-title"><strong>Mittelfrist und Langfrist</strong><span>Jahressicht · strategische Schätzung</span></div><div class="long-grid">${years.map(y=>{const items=state.projects.filter(p=>y==="10+"?parseInt(p.startYear||p.startQuarter,10)>2036:parseInt(p.startYear||p.startQuarter,10)===y);return `<div class="year-bucket"><strong>${y==="10+"?"> 10 Jahre":y}</strong><b>${items.length}</b><span>${items.slice(0,2).map(x=>esc(x.object)).join(" · ")||"keine Einordnung"}</span></div>`}).join("")}</div>`}
function renderDetail(){let p=state.projects.find(x=>x.id===selectedId);if(!p){p=state.projects[0];selectedId=p?.id}if(!p){$("#project-detail").innerHTML='<div class="empty-note">Noch kein Projekt vorhanden.</div>';return}const r=readiness(p),pi=phaseIndex(p.phaseKey),next=p.milestones.find(m=>qIndex(m.quarter)>=qIndex(START_QUARTER))||p.milestones.at(-1);const people=p.demands.slice().sort((a,b)=>qIndex(a.quarter)-qIndex(b.quarter)).slice(0,4);$("#project-detail").innerHTML=`
  <div class="project-cover"><div class="meta"><span>${esc(p.kind)} · ${esc(p.startQuarter)} bis ${esc(p.endQuarter)}</span><span class="status-chip">${esc(r.label)}</span></div><h3>${esc(p.object)}</h3><p>${esc(p.measure)}</p></div>
  <div class="project-body"><div class="next-box"><span>Nächster markierter Übergang</span><strong>${esc(next?.name||p.nextDecision||"offen")}</strong><small>${next?.quarter?qLabel(next.quarter):"Termin offen"} · ${esc(next?.owner||"Baukommission")}</small></div>
  <span class="section-label">Normprozess</span><div class="phase-steps">${PHASES.map((ph,i)=>`<i class="phase-step ${ph.className} ${i<pi?"done":i===pi?"current":""}" title="${esc(ph.label)}"></i>`).join("")}</div>
  <span class="section-label">Vier Planungsperspektiven</span><div class="perspectives"><div class="perspective"><span>Inhalt und Reifegrad</span><strong>${esc(PHASES[pi].label)}</strong></div><div class="perspective"><span>Rollen und Menschen</span><strong>${p.demands.length?`${p.demands.length} Einsätze`:"noch offen"}</strong></div><div class="perspective"><span>Kosten und Finanzierung</span><strong>${chf(knownCost(p),true)}</strong></div><div class="perspective"><span>Zeit und Meilensteine</span><strong>${p.startQuarter} – ${p.endQuarter}</strong></div></div>
  <span class="section-label">Ressourcen dieses Projekts</span><div class="mini-resources">${people.length?people.map(x=>`<div class="mini-resource"><div><strong>${esc(x.name)} · ${esc(x.function)}</strong><span>${qLabel(x.quarter)} · ${esc(PHASES[phaseIndex(x.phaseKey||p.phaseKey)].short)}</span></div><b>${num(x.min)}–${num(x.max)} PT</b></div>`).join(""):'<div class="empty-note">Noch kein Bedarf eingetragen.</div>'}</div>
  <div class="project-actions"><button class="button primary" data-edit-project="${esc(p.id)}">Projekt öffnen</button><button class="button ghost" data-focus-resource="${esc(people[0]?.name||"")}">Wirkung sehen</button></div>${changedProject(p)?`<button class="restore-link" data-restore="${esc(p.id)}">Excel Ausgangsstand für dieses Projekt wiederherstellen</button>`:""}</div>`}

function capacityFor(name,q){const rows=state.capacities.filter(x=>x.name===name&&x.quarter===q);return {min:rows.reduce((s,x)=>s+num(x.min),0),max:rows.reduce((s,x)=>s+num(x.max),0)}}
function demandFor(name,q){const rows=state.projects.flatMap(p=>p.demands||[]).filter(x=>x.name===name&&x.quarter===q);return {min:rows.reduce((s,x)=>s+num(x.min),0),max:rows.reduce((s,x)=>s+num(x.max),0)}}
function resourceNames(){return [...new Set([...state.capacities.map(x=>x.name),...state.projects.flatMap(p=>(p.demands||[]).map(x=>x.name))])].filter(Boolean).sort((a,b)=>a.localeCompare(b,"de"))}
function resourceState(d,c){if(!d.max&&!c.max)return "open";if(d.max&&!c.max)return "open";if(d.max<=c.min)return "ok";if(d.min>c.max)return "gap";return "watch"}
function renderResources(){
  const names=resourceNames();const focusSelect=$("#resource-focus"),previous=focusSelect.value;focusSelect.innerHTML=names.length?names.map(n=>`<option>${esc(n)}</option>`).join(""):'<option>Keine Ressource</option>';if(names.includes(previous))focusSelect.value=previous;const focus=focusSelect.value,max=Math.max(1,...DISPLAY_QUARTERS.flatMap(q=>{const d=demandFor(focus,q),c=capacityFor(focus,q);return[d.max,c.max]}));
  $("#resource-chart").innerHTML=DISPLAY_QUARTERS.map(q=>{const d=demandFor(focus,q),c=capacityFor(focus,q);return `<div class="resource-column"><div class="bar-space"><div class="capacity-range" style="height:${c.max/max*100}%" title="Verfügbar ${c.min}–${c.max} PT"></div><div class="demand-range" style="height:${d.max/max*100}%" title="Bedarf ${d.min}–${d.max} PT"></div></div><b class="bar-value">${d.max||c.max?`${d.min}–${d.max} / ${c.min}–${c.max}`:"–"}</b><small>${qLabel(q)}</small></div>`}).join("");
  $("#capacity-count").textContent=`${state.capacities.length} Einträge`;
  $("#capacity-list").innerHTML=state.capacities.length?state.capacities.slice().sort((a,b)=>qIndex(a.quarter)-qIndex(b.quarter)).map(x=>`<div class="capacity-list-row" data-edit-capacity="${esc(x.id)}"><div><strong>${esc(x.name)} · ${esc(x.function)}</strong><span>${qLabel(x.quarter)}</span></div><b>${num(x.min)}–${num(x.max)} PT</b><span>›</span></div>`).join(""):'<div class="empty-note">Noch keine Verfügbarkeit eingetragen.</div>';
  const matrixNames=names,quarters=DISPLAY_QUARTERS.filter(q=>matrixNames.some(n=>demandFor(n,q).max||capacityFor(n,q).max));
  $("#resource-matrix").innerHTML=matrixNames.length&&quarters.length?`<table class="resource-matrix"><thead><tr><th>Ressource · Bedarf / verfügbar</th>${quarters.map(q=>`<th>${qLabel(q)}</th>`).join("")}</tr></thead><tbody>${matrixNames.map(n=>`<tr><td><strong>${esc(n)}</strong></td>${quarters.map(q=>{const d=demandFor(n,q),c=capacityFor(n,q),s=resourceState(d,c);return `<td class="matrix-cell ${s}" title="Bedarf ${d.min}–${d.max} PT · verfügbar ${c.min}–${c.max} PT">${d.min}–${d.max}<br><small>${c.min}–${c.max}</small></td>`}).join("")}</tr>`).join("")}</tbody></table>`:'<div class="empty-note">Sobald Bedarf und Verfügbarkeit eingetragen sind, erscheint hier die gemeinsame Belastungssicht.</div>';
}
function renderFinance(){const years=Array.from({length:11},(_,i)=>2026+i),totals=years.map(y=>state.projects.reduce((s,p)=>{const precise=(p.quarterCosts||[]).filter(x=>x.quarter.startsWith(String(y))).reduce((a,x)=>a+num(x.amount),0);if(precise)return s+precise;return s+(p.cashflow||[]).filter(x=>x.year==y&&x.status==="bekannt").reduce((a,x)=>a+num(x.amount),0)},0)),max=Math.max(1,...totals);$("#finance-chart").innerHTML=years.map((y,i)=>`<div class="finance-year"><strong>${totals[i]?chf(totals[i],true):"offen"}</strong><div class="finance-bar" style="height:${totals[i]/max*88}%"></div><span>${y}</span></div>`).join("")}

function openProject(id,newProject=false){let p=state.projects.find(x=>x.id===id);if(newProject)p=normalizeProject({id:`neu-${Date.now()}`,object:"",measure:"",kind:"Bauprojekt",phaseKey:"anlass",startQuarter:START_QUARTER,endQuarter:"2027-Q2",roles:{gs:"offen",bk:"offen",vs:"nach Bedarf",bhb:"offen",control:"offen",deputy:"offen"},demands:[],quarterCosts:[],cashflow:[],nextDecision:""});if(!p)return;$("#project-id").value=p.id;$("#project-dialog-title").textContent=newProject?"Neues Projekt":p.object;$("#f-object").value=p.object;$("#f-measure").value=p.measure;$("#f-kind").value=p.kind;$("#f-phase").value=p.phaseKey;$("#f-start").value=p.startQuarter;$("#f-end").value=p.endQuarter;$("#f-cost").value=p.cost||"";$("#f-accuracy").value=normalizeAccuracy(p.accuracy);$("#f-approved").value=p.approved||"no";$("#f-next").value=p.nextDecision||"";$("#f-gs").value=p.roles.gs||"offen";$("#f-bk").value=p.roles.bk||"offen";$("#f-vs").value=p.roles.vs||"nach Bedarf";$("#f-bhb").value=p.roles.bhb||"offen";$("#f-control").value=p.roles.control||"offen";$("#f-deputy").value=p.roles.deputy||"offen";editDemands=clone(p.demands||[]);editCosts=clone(p.quarterCosts||[]);editMilestones=clone(p.milestones||defaultMilestones(p));renderDemandEditor();renderFinanceEditor();renderMilestones();$("#delete-project").classList.toggle("hidden",newProject);setFormTab("base");$("#project-dialog").showModal()}
function normalizeAccuracy(a){const s=String(a||"");if(s.includes("10"))return "±10 %";if(s.includes("25"))return "±25 %";if(s.includes("Schätzung"))return "Erste Schätzung";return "offen"}
function setFormTab(name){$$('[data-form-tab]').forEach(b=>b.classList.toggle("active",b.dataset.formTab===name));$$('[data-panel]').forEach(p=>p.classList.toggle("hidden",p.dataset.panel!==name))}
function renderDemandEditor(){$("#demand-editor").innerHTML=editDemands.length?editDemands.map((x,i)=>`<div class="edit-row" data-demand="${i}"><label><span>Name</span><input class="d-name" value="${esc(x.name)}" placeholder="Person/Firma"></label><label><span>Funktion</span><input class="d-function" value="${esc(x.function)}" placeholder="BK/BHB"></label><label><span>Quartal</span><select class="d-quarter">${quarterOptions(x.quarter)}</select></label><label><span>PT min.</span><input class="d-min" type="number" min="0" step=".5" value="${esc(x.min)}"></label><label><span>PT max.</span><input class="d-max" type="number" min="0" step=".5" value="${esc(x.max)}"></label><button type="button" class="remove" data-remove-demand="${i}">×</button></div>`).join(""):'<div class="empty-note">Noch kein Bedarf. Mit «+ Bedarf» eine Quartalszeile hinzufügen.</div>'}
function renderFinanceEditor(){$("#finance-editor").innerHTML=editCosts.length?editCosts.map((x,i)=>`<div class="edit-row finance" data-cost="${i}"><label><span>Quartal</span><select class="fc-quarter">${quarterOptions(x.quarter)}</select></label><label><span>Betrag CHF</span><input class="fc-amount" inputmode="decimal" value="${esc(x.amount)}"></label><button type="button" class="remove" data-remove-cost="${i}">×</button></div>`).join(""):'<div class="empty-note">Keine Quartalswerte. Die bekannten Jahreswerte bleiben in der Gesamtsicht sichtbar.</div>'}
function renderMilestones(){$("#milestone-editor").innerHTML=editMilestones.map((m,i)=>`<div class="milestone-row ${m.major?"major":""}"><i></i><div><strong>${esc(m.name)}</strong><span>${esc(m.owner)}${m.major?" · grosser Entscheid":""}</span></div><select data-milestone="${i}"><option value="">Termin offen</option>${quarterOptions(m.quarter)}</select></div>`).join("")}
function quarterOptions(selected){return ALL_QUARTERS.map(q=>`<option value="${q}" ${q===selected?"selected":""}>${qLabel(q)}</option>`).join("")}
function syncEditors(){editDemands=$$("[data-demand]").map(row=>({id:editDemands[Number(row.dataset.demand)]?.id||`d-${Date.now()}-${row.dataset.demand}`,name:row.querySelector(".d-name").value.trim(),function:row.querySelector(".d-function").value.trim(),quarter:row.querySelector(".d-quarter").value,min:num(row.querySelector(".d-min").value),max:num(row.querySelector(".d-max").value),phaseKey:$("#f-phase").value})).filter(x=>x.name&&x.function);editCosts=$$("[data-cost]").map((row,i)=>({id:editCosts[i]?.id||`f-${Date.now()}-${i}`,quarter:row.querySelector(".fc-quarter").value,amount:row.querySelector(".fc-amount").value})).filter(x=>num(x.amount));editMilestones=$$("[data-milestone]").map((s,i)=>({...editMilestones[i],quarter:s.value}))}

function openCapacity(id){const c=state.capacities.find(x=>x.id===id)||{id:"",name:"",function:"",quarter:"2027-Q1",min:"",max:""};$("#c-id").value=c.id;$("#c-name").value=c.name;$("#c-function").value=c.function;$("#c-quarter").value=c.quarter;$("#c-min").value=c.min;$("#c-max").value=c.max;$("#delete-capacity").classList.toggle("hidden",!id);$("#capacity-dialog").showModal()}
function csv(name,rows){const content="\ufeff"+rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob([content],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

$("#phase-filter").innerHTML+=""+PHASES.map(p=>`<option value="${p.key}">${p.label}</option>`).join("");$("#f-phase").innerHTML=PHASES.map(p=>`<option value="${p.key}">${p.label}</option>`).join("");const qopts=quarterOptions("");$("#f-start").innerHTML=qopts;$("#f-end").innerHTML=qopts;$("#c-quarter").innerHTML=qopts;
[$("#search"),$("#kind-filter"),$("#phase-filter"),$("#only-pressure")].forEach(el=>el.addEventListener("input",renderTimeline));
$("#timeline").addEventListener("click",e=>{const row=e.target.closest("[data-select]");if(row){selectedId=row.dataset.select;renderTimeline();renderDetail()}});
$("#project-detail").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-project]");if(edit)openProject(edit.dataset.editProject);const restore=e.target.closest("[data-restore]");if(restore){const b=BASELINE.find(x=>x.id===restore.dataset.restore);if(b&&confirm("Lokale Änderungen dieses Projekts verwerfen?")){snapshot("Projekt wiederhergestellt");const i=state.projects.findIndex(x=>x.id===b.id);state.projects[i]=clone(b);save();toast("Excel Ausgangsstand wiederhergestellt")}}const focus=e.target.closest("[data-focus-resource]");if(focus?.dataset.focusResource){$("#resource-focus").value=focus.dataset.focusResource;renderResources();$("#ressourcen").scrollIntoView({behavior:"smooth"})}});
$("#edit-selected").addEventListener("click",()=>openProject(selectedId));$("#new-project").addEventListener("click",()=>openProject(null,true));$("#expand-long").addEventListener("click",()=>{longOpen=!longOpen;renderLongHorizon()});
$$('[data-form-tab]').forEach(b=>b.addEventListener("click",()=>setFormTab(b.dataset.formTab)));
$("#add-demand").addEventListener("click",()=>{syncEditors();editDemands.push({id:`d-${Date.now()}`,name:"",function:"",quarter:"2027-Q1",min:"",max:"",phaseKey:$("#f-phase").value});renderDemandEditor()});
$("#demand-editor").addEventListener("click",e=>{const b=e.target.closest("[data-remove-demand]");if(b){syncEditors();editDemands.splice(Number(b.dataset.removeDemand),1);renderDemandEditor()}});
$("#add-finance").addEventListener("click",()=>{syncEditors();editCosts.push({id:`f-${Date.now()}`,quarter:"2027-Q1",amount:""});renderFinanceEditor()});
$("#finance-editor").addEventListener("click",e=>{const b=e.target.closest("[data-remove-cost]");if(b){syncEditors();editCosts.splice(Number(b.dataset.removeCost),1);renderFinanceEditor()}});
$("#project-form").addEventListener("submit",e=>{e.preventDefault();syncEditors();const id=$("#project-id").value,existing=state.projects.find(x=>x.id===id);const p=normalizeProject({...existing,id,object:$("#f-object").value.trim(),measure:$("#f-measure").value.trim(),kind:$("#f-kind").value,phaseKey:$("#f-phase").value,startQuarter:$("#f-start").value,endQuarter:$("#f-end").value,cost:$("#f-cost").value,accuracy:$("#f-accuracy").value,approved:$("#f-approved").value,nextDecision:$("#f-next").value.trim(),roles:{gs:$("#f-gs").value.trim()||"offen",bk:$("#f-bk").value.trim()||"offen",vs:$("#f-vs").value.trim()||"nach Bedarf",bhb:$("#f-bhb").value.trim()||"offen",control:$("#f-control").value.trim()||"offen",deputy:$("#f-deputy").value.trim()||"offen"},demands:editDemands,quarterCosts:editCosts,milestones:editMilestones,startYear:$("#f-start").value.slice(0,4),endYear:$("#f-end").value.slice(0,4),category:$("#f-kind").value});snapshot(existing?"Projekt geändert":"Projekt erstellt");if(existing)state.projects[state.projects.findIndex(x=>x.id===id)]=p;else state.projects.push(p);selectedId=id;save();$("#project-dialog").close();toast("Projekt gespeichert")});
$("#delete-project").addEventListener("click",()=>{const id=$("#project-id").value,p=state.projects.find(x=>x.id===id);if(p&&confirm(`Projekt «${p.object}» aus dem Arbeitsstand löschen? Die Excel Mutter bleibt unverändert.`)){snapshot("Projekt gelöscht");state.projects=state.projects.filter(x=>x.id!==id);if(BASELINE.some(x=>x.id===id))state.deletedIds.push(id);selectedId=state.projects[0]?.id;save();$("#project-dialog").close();toast("Projekt im Arbeitsstand gelöscht")}});
$("#new-capacity").addEventListener("click",()=>openCapacity());$("#capacity-list").addEventListener("click",e=>{const row=e.target.closest("[data-edit-capacity]");if(row)openCapacity(row.dataset.editCapacity)});$("#resource-focus").addEventListener("change",renderResources);
$("#capacity-form").addEventListener("submit",e=>{e.preventDefault();const id=$("#c-id").value||`cap-${Date.now()}`,entry={id,name:$("#c-name").value.trim(),function:$("#c-function").value.trim(),quarter:$("#c-quarter").value,min:num($("#c-min").value),max:num($("#c-max").value)};if(entry.max<entry.min){toast("Höchstwert muss mindestens dem Mindestwert entsprechen");return}snapshot($("#c-id").value?"Verfügbarkeit geändert":"Verfügbarkeit ergänzt");const i=state.capacities.findIndex(x=>x.id===id);if(i>=0)state.capacities[i]=entry;else state.capacities.push(entry);save();$("#capacity-dialog").close();toast("Verfügbarkeit übernommen")});
$("#delete-capacity").addEventListener("click",()=>{const id=$("#c-id").value;if(id&&confirm("Diesen Kapazitätseintrag löschen?")){snapshot("Verfügbarkeit gelöscht");state.capacities=state.capacities.filter(x=>x.id!==id);save();$("#capacity-dialog").close()}});
$("#undo").addEventListener("click",()=>{const prev=history.pop();if(!prev)return;state=prev.state;localStorage.setItem(HISTORY_KEY,JSON.stringify(history));save();toast(`Rückgängig: ${prev.label}`)});
$("#reset-all").addEventListener("click",()=>{if(confirm("Alle lokalen Änderungen verwerfen und den Excel Ausgangsstand wiederherstellen?")){snapshot("Arbeitsstand zurückgesetzt");state={projects:clone(BASELINE),capacities:clone(EXAMPLE_CAPACITIES),deletedIds:[]};selectedId=state.projects[0]?.id;save();toast("Arbeitsstand zurückgesetzt")}});
$("#export-projects").addEventListener("click",()=>csv("BGR_Projekte.csv",[["Projekt-ID","Objekt","Massnahme","Projektart","Projektphase","Start","Ende","Kosten CHF","Kostengenauigkeit","GS","BK","VS","BHB","Kontrolle","Stellvertretung","Nächster Entscheid"],...state.projects.map(p=>[p.id,p.object,p.measure,p.kind,PHASES[phaseIndex(p.phaseKey)].label,p.startQuarter,p.endQuarter,p.cost,p.accuracy,p.roles.gs,p.roles.bk,p.roles.vs,p.roles.bhb,p.roles.control,p.roles.deputy,p.nextDecision])]));
$("#export-resources").addEventListener("click",()=>csv("BGR_Projektbedarf.csv",[["Projekt-ID","Objekt","Name","Funktion","Quartal","Projektphase","PT min","PT max"],...state.projects.flatMap(p=>(p.demands||[]).map(d=>[p.id,p.object,d.name,d.function,d.quarter,PHASES[phaseIndex(d.phaseKey||p.phaseKey)].label,d.min,d.max]))]));
$("#export-capacity").addEventListener("click",()=>csv("BGR_Verfuegbarkeit.csv",[["Name","Funktion","Quartal","PT min","PT max"],...state.capacities.map(x=>[x.name,x.function,x.quarter,x.min,x.max])]));
$("#export-changes").addEventListener("click",()=>csv("BGR_Aenderungsprotokoll.csv",[["Typ","Projekt-ID","Objekt","Hinweis"],...state.projects.filter(changedProject).map(p=>[BASELINE.some(x=>x.id===p.id)?"geändert":"neu",p.id,p.object,"lokaler Arbeitsstand"]),...state.deletedIds.map(id=>["gelöscht",id,BASELINE.find(x=>x.id===id)?.object||"","nur im lokalen Arbeitsstand"])]));

renderAll();
