export const BASELINE_PROJECTS = [
  {
    "id": "tg-ruopigenring",
    "object": "Tiefgarage Ruopigenring 37–57",
    "measure": "Statische Ertüchtigung und Sanierung Tiefgarage",
    "category": "Bauprojekt",
    "strategy": "Werterhaltung",
    "phase": "33 - Baubewilligungsphase",
    "horizon": "0–12 Monate",
    "startYear": "2024",
    "endYear": "2027",
    "cost": "1850000",
    "accuracy": "offen",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "Iris persönlich",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Verfügbarkeit und Ausführungsorganisation absichern",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2024",
        "amount": "12500",
        "status": "bekannt"
      },
      {
        "year": "2025",
        "amount": "136500",
        "status": "bekannt"
      },
      {
        "year": "2026",
        "amount": "701000",
        "status": "bekannt"
      },
      {
        "year": "2027",
        "amount": "1000000",
        "status": "bekannt"
      }
    ],
    "resources": []
  },
  {
    "id": "staffelnhof-1",
    "object": "Staffelnhofstrasse 1",
    "measure": "Fernwärmeanschluss",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "-",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "2027",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Geschäftsstelle",
    "bgrResponsibility": "Geschäftsstelle",
    "projectManagement": "Geschäftsstelle",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Umfang und Ressourcen für den Anschluss bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2026",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2027",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "staffelnhof-3-5",
    "object": "Staffelnhofstrasse 3 + 5",
    "measure": "Neubau",
    "category": "Umbauprojekt",
    "strategy": "Ersatzneubau",
    "phase": "32 - Bauprojekt",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "2029",
    "cost": "9119850",
    "accuracy": "offen",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Projektleitung und benötigte Leistungen je Phase zuweisen",
    "note": "Projektkategorie in den bestehenden Tabellen nicht einheitlich. Hier gemäss Projektübersicht als Umbauprojekt geführt.",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2026",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2027",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2029",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "eichenstrasse-21",
    "object": "Eichenstrasse 21",
    "measure": "Dachaufstockung und Gebäudehüllensanierung",
    "category": "Umbauprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "13–36 Monate",
    "startYear": "2027",
    "endYear": "2030",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Machbarkeit und interne Auftraggeberrolle klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2027",
        "amount": "5000",
        "status": "bekannt"
      },
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2029",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2030",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "obermaettli-5-dach",
    "object": "Obermättlistrasse 5",
    "measure": "Dachaufstockung inklusive Gebäudehüllensanierung",
    "category": "Umbauprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "13–36 Monate",
    "startYear": "2027",
    "endYear": "2030",
    "cost": "",
    "accuracy": "(+/- 10%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Machbarkeitsstudie beauftragen und Umbaupotential klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2027",
        "amount": "5000",
        "status": "bekannt"
      },
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2029",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2030",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "ruopigenplatz-28",
    "object": "Ruopigenplatz 28",
    "measure": "Ersatz Küchen, Sanierung Vordach und Eingangstreppe",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "-",
    "horizon": "0–12 Monate",
    "startYear": "2027",
    "endYear": "2027",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Geschäftsstelle",
    "bgrResponsibility": "Geschäftsstelle",
    "projectManagement": "Geschäftsstelle",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Abgrenzung Unterhalt und Projektpass sowie Ressourcen klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2027",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "hauptstrasse-54",
    "object": "Hauptstrasse 54",
    "measure": "Gebäudehülle",
    "category": "Bauprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "33 - Baubewilligungsphase",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "offen",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Weiteres Vorgehen und Zieltermin bestimmen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2026",
        "amount": "10000",
        "status": "bekannt"
      }
    ],
    "resources": []
  },
  {
    "id": "taeschmattstrasse-7",
    "object": "Täschmattstrasse 7",
    "measure": "Dachaufstockung und Gebäudehüllensanierung",
    "category": "Umbauprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "2030",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Phasen und Ressourcen zuweisen",
    "note": "Projektkategorie in den bestehenden Tabellen nicht einheitlich.",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2026",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2027",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2029",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2030",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "reusszopf",
    "object": "Neubau Reusszopf",
    "measure": "Neubau",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "52 - Ausführung",
    "horizon": "0–12 Monate",
    "startYear": "2025",
    "endYear": "2028",
    "cost": "20000000",
    "accuracy": "offen",
    "currentOwner": "Andreas Stirnimann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "andere externe Partner",
    "provider": "andere externe Partner",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Interne Auftraggeberrolle für Abschlussphase bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ruopigenhoehe-14-15",
    "object": "Ruopigenhöhe 14 + 15",
    "measure": "Flachdach, Küchen, Elektroverteilung und Holzfenster sanieren",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2028",
    "endYear": "2031",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Vorhaben bündeln und zeitlich einordnen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ruopigenring-39-57",
    "object": "Ruopigenring 39–57",
    "measure": "Küchensanierung",
    "category": "Bauprojekt",
    "strategy": "Werterhaltung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2028",
    "endYear": "2030",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Objektumfang und Planungstakt bestätigen",
    "note": "In der Zeitachse als Ruopigenring 39–51 bezeichnet.",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2029",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2030",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "staldenhoehe-26",
    "object": "Staldenhöhe 26",
    "measure": "Einfache Badsanierung",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "33 - Baubewilligungsphase",
    "horizon": "3–10 Jahre",
    "startYear": "2028",
    "endYear": "2028",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Iris Ammann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Zuständigkeit und Ausführungsressourcen bestimmen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2028",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "hauptstrasse-38",
    "object": "Hauptstrasse 38",
    "measure": "Ersatzneubau",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2030",
    "endYear": "2035",
    "cost": "9000000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Erste Auftraggeber und Ressourcenlogik bestimmen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [
      {
        "year": "2030",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2031",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2032",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2033",
        "amount": "",
        "status": "offen"
      },
      {
        "year": "2034",
        "amount": "",
        "status": "offen"
      }
    ],
    "resources": []
  },
  {
    "id": "obermaettli-23-34",
    "object": "Obermättlistrasse 23–34",
    "measure": "Umstellung Wärmeerzeugung, Photovoltaik und Flachdach",
    "category": "Grossprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "21 - Machbarkeitsstudie",
    "horizon": "0–12 Monate",
    "startYear": "2025",
    "endYear": "2027",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Andreas Stirnimann",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Projektkategorie und nächste Phase bestätigen",
    "note": "Projektkategorie in Strategie und Zeitachse nicht einheitlich.",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-5-unterhalt",
    "object": "Obermättlistrasse 5",
    "measure": "Dachuntersicht, Balkonkosmetik und Küchengeräte",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "U - Unterhalt",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "2026",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "Geschäftsstelle",
    "bgrResponsibility": "Geschäftsstelle",
    "projectManagement": "Geschäftsstelle",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Als Unterhalt abschliessen oder mit Dachprojekt bündeln",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "vorder-ruopigen",
    "object": "Vorder Ruopigen",
    "measure": "Neubau und Arealentwicklung",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "150000000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "andere externe Partner",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Interne Auftraggeberrolle und externe Mandatierung bestimmen",
    "note": "Zeitraum ist eine erste Einordnung aus der mittelfristigen Strategie.",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ckw-areal",
    "object": "CKW Areal",
    "measure": "Neubau und Arealentwicklung",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "35000000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "Baukommission",
    "projectManagement": "andere externe Partner",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Partnerschaft, Einfluss und BGR Ressourcen klären",
    "note": "Zeitraum ist eine erste Einordnung aus der mittelfristigen Strategie.",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettliweg-1-5-4",
    "object": "Obermättliweg 1 + 3 + 5 + 4",
    "measure": "Ersatz Wärmeerzeugung, Balkone, Fenster, Dach und Fassade",
    "category": "Bauprojekt",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Massnahmen bündeln und erste Machbarkeit bestimmen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "rothenhalde-1-3",
    "object": "Rothenhalde 1–3",
    "measure": "Küchen und Bäder",
    "category": "offen",
    "strategy": "Werterhaltung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "500000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Projektart, Zustand und Zieljahr bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ruopigenring-37-brandschutz",
    "object": "Ruopigenring 37",
    "measure": "Brandschutz und Fassade",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Abgrenzung zur Tiefgarage und Projektumfang klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "strassenbaugenossenschaft",
    "object": "Strassenbaugenossenschaft",
    "measure": "Pfisternweg bis Restaurant Reusszopf",
    "category": "offen",
    "strategy": "zu definieren",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Rolle der BGR und Abhängigkeiten zu Partnern klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-16",
    "object": "Obermättlistrasse 16",
    "measure": "Gebäudehülle",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Zustand und Priorität bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "staffelnweg-3",
    "object": "Staffelnweg 3",
    "measure": "Gebäudehülle",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Zustand und Priorität bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ruopigenring-107-113-huelle",
    "object": "Ruopigenring 107–113",
    "measure": "Gebäudehülle",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Mittelfristige Massnahme und kurzfristigen Unterhalt abgrenzen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-23-kuechen",
    "object": "Obermättlistrasse 23",
    "measure": "Küchen, Bäder und Gebäudehülle",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Abgrenzung zum Bündel Obermättlistrasse 23–34 klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-25",
    "object": "Obermättlistrasse 25",
    "measure": "Gebäudehülle",
    "category": "offen",
    "strategy": "Umfassende Erneuerung",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Abgrenzung zum Bündel Obermättlistrasse 23–34 klären",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "fluhmuehle-11-13",
    "object": "Fluhmühle 11 + 13",
    "measure": "Mögliches Vorhaben gemäss Zeitachse",
    "category": "offen",
    "strategy": "zu definieren",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Bestätigen, ob und mit welchem Umfang das Vorhaben ins Portfolio gehört",
    "note": "",
    "uncertain": true,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "hauptstrasse-36",
    "object": "Hauptstrasse 36",
    "measure": "Mögliches Vorhaben gemäss Zeitachse",
    "category": "offen",
    "strategy": "zu definieren",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Bestätigen, ob und mit welchem Umfang das Vorhaben ins Portfolio gehört",
    "note": "",
    "uncertain": true,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "sandeggstrasse-1-mittel",
    "object": "Sandeggstrasse 1",
    "measure": "Mögliches Vorhaben gemäss mittelfristiger Zeitachse",
    "category": "offen",
    "strategy": "zu definieren",
    "phase": "-",
    "horizon": "3–10 Jahre",
    "startYear": "2029",
    "endYear": "2036",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Mittelfristige Massnahme bestätigen oder mit langfristigem Ersatzneubau zusammenführen",
    "note": "",
    "uncertain": true,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "ruopigenring-107-113-unterhalt",
    "object": "Ruopigenring 107–113",
    "measure": "Kurzfristige Unterhaltsmassnahme gemäss Zeitachse",
    "category": "Umbauprojekt",
    "strategy": "Werterhaltung",
    "phase": "U - Unterhalt",
    "horizon": "0–12 Monate",
    "startYear": "2026",
    "endYear": "2026",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "Geschäftsstelle",
    "projectManagement": "Geschäftsstelle",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Massnahme und Abschluss bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "sandeggstrasse-1-lang",
    "object": "Sandeggstrasse 1",
    "measure": "Ersatzneubau oder Erweiterung",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2037",
    "endYear": "offen",
    "cost": "",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Langfristige Option und Zeithorizont bestätigen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-5-lang",
    "object": "Obermättlistrasse 5",
    "measure": "Ersatzneubau oder Erweiterung",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2036",
    "endYear": "2036",
    "cost": "2800000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Langfristige Option gegenüber heutigen Erneuerungsprojekten einordnen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-34-lang",
    "object": "Obermättlistrasse 34",
    "measure": "Ersatzneubau",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2040",
    "endYear": "2040",
    "cost": "5000000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Erste Annahme im rollenden Portfolio führen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "staldenhoehe-lang",
    "object": "Staldenhöhe",
    "measure": "Ersatzneubau",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2047",
    "endYear": "2047",
    "cost": "40000000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Erste Annahme im rollenden Portfolio führen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettliweg-lang",
    "object": "Obermättliweg 1 + 3 + 5",
    "measure": "Ersatzneubau",
    "category": "Grossprojekt",
    "strategy": "Ersatzneubau",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2051",
    "endYear": "2051",
    "cost": "9630000",
    "accuracy": "Erste Schätzung",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Erste Annahme im rollenden Portfolio führen",
    "note": "",
    "uncertain": false,
    "archived": false,
    "cashflow": [],
    "resources": []
  },
  {
    "id": "obermaettli-18",
    "object": "Obermättlistrasse 18",
    "measure": "Laufen lassen",
    "category": "offen",
    "strategy": "zu definieren",
    "phase": "-",
    "horizon": "> 10 Jahre",
    "startYear": "2051",
    "endYear": "offen",
    "cost": "",
    "accuracy": "(+/- 50%)",
    "currentOwner": "noch nicht definiert",
    "bgrResponsibility": "offen",
    "projectManagement": "offen",
    "provider": "offen",
    "control": "offen",
    "deputy": "offen",
    "handover": "",
    "decisionOwner": "offen",
    "decisionDue": "",
    "exceptionAction": "offen",
    "financeStatus": "in Klärung",
    "nextDecision": "Bedeutung von «Laufen lassen» und nächsten Prüfzeitpunkt definieren",
    "note": "",
    "uncertain": true,
    "archived": false,
    "cashflow": [],
    "resources": []
  }
];
